steps:
  - id: 'tf-init'
    name: 'hashicorp/terraform:latest'
    entrypoint: 'sh'
    args: 
    - '-c'
    - | 
        echo "Initializing Terraform..."
        terraform init -backend-config="bucket=$_TF_STATE_BUCKET_NAME" -backend-config="prefix=terraform/state"
  # - timeout: "600s"

  - name: "hashicorp/terraform:latest"
    id: Terraform Plan
    entrypoint: "sh"
    args:
      - "-c"
      - |
        echo "Running Terraform Plan..."
        terraform plan \
          -var "project_id=$_PROJECT_ID" \
          -var "subnet_cidr=$_SUBNET_CIDR" \
          -var "subnet_region=$_SUBNET_REGION" \
          -var "subnet_zone=$_SUBNET_ZONE" \
          -var "region=$_REGION"

  - name: "hashicorp/terraform:latest"
    id: Terraform Apply
    entrypoint: "sh"
    args:
      - "-c"
      - |
        echo "Applying Terraform..."
        terraform apply -auto-approve \
          -var "project_id=$_PROJECT_ID" \
          -var "subnet_cidr=$_SUBNET_CIDR" \
          -var "subnet_region=$_SUBNET_REGION" \
          -var "subnet_zone=$_SUBNET_ZONE" \
          -var "region=$_REGION"


options:
  logging: CLOUD_LOGGING_ONLY
